# Etapa 1: Construcción
FROM node:20 AS builder

# Crear carpeta y copiar archivos
WORKDIR /app
COPY . .

# Instalar dependencias y construir la app
RUN npm install
RUN npm run build

# Etapa 2: Producción
FROM node:20-alpine AS runner

RUN apk add --no-cache wrk


WORKDIR /app
COPY --from=builder /app ./

# Variables de entorno opcionales
ENV NODE_ENV=production

EXPOSE 3000

# Comando de inicio
CMD ["npm", "start"]
